library(reshape2)
library(fastcluster)
library(optparse)
library(data.table)
library(ape)

dset <- read.table(file = "ALL_BINS_MASH_DISTANCE_edited.txt", header = TRUE, sep = '\t')
dist.dset = acast(dset, genome1~genome2, value.var="dist")
message("Clustering...\n")
hc = hclust(as.dist(dist.dset))
message(paste("Cutting clusters at 95%, 97% and 99% ANI\n"))
memb_99 = cutree(hc, h=0.01) 
memb_97 = cutree(hc, h=0.03)
memb_95 = cutree(hc, h=0.05)
memb_90 = cutree(hc, h=0.10)
clusters_99 = unique(memb_99)
clusters_97 = unique(memb_97)
clusters_95 = unique(memb_95)
clusters_90 = unique(memb_90)
ngroups_99 = length(clusters_99)
ngroups_97 = length(clusters_97)
ngroups_95 = length(clusters_95)
ngroups_90 = length(clusters_90)
cat(paste("90% clusters:", ngroups_90,"\t", "95% clusters:", ngroups_95,"\t", "97% clusters:", ngroups_97, "\t", "99% clusters:", ngroups_99, "\n"))

# save tree
species_tree = as.phylo(hc)
dir.create("trees_26")
write.tree(phy=species_tree, file="trees_26/mashtree.nwk")
